# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 400f11e667a5bc78463311b35795743224a441f8fc0d79df37501de07ff836be561244c3141ea3768cfea727bb1d7f73ed443e73eb3e34a4af30c796f8ec06df

test:
  secret_key_base: 879c6b55f9eb0131a2aa699cce99962bf6f7d4eea6e560e5f2b80e923657a322e6f7f3cf8c5c39b242856b47f33d2f6717ecaf18e75e4be24659bb1c17eac950

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
